[training]
learning_rate = 0.00045
model_version = 108
checkpoint = 1
epochs = 10
log_interval = 1
checkpoint_interval = 5
batch_size = 32
batch_sample = 4
train_ratio = 0.8
device = "auto"
weight_decay = 0.08
grad_clip = 3.9